Repository cagov/covid-static-data, pull requests merged in 2021-10, with the labels that each got.

#823 2021-10-01 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#819 2021-10-01 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#829 2021-10-02 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#825 2021-10-02 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#838 2021-10-03 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#834 2021-10-03 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#844 2021-10-04 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#840 2021-10-04 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#854 2021-10-05 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#853 2021-10-05 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#865 2021-10-06 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:35 a.m. ☀️
