Repository cagov/covid-static-data, pull requests merged in 2021-06, with the labels that each got.

#172 2021-06-01 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#178 2021-06-02 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#180 2021-06-02 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#184 2021-06-03 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#188 2021-06-04 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#192 2021-06-05 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#196 2021-06-06 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#200 2021-06-07 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#204 2021-06-08 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#211 2021-06-09 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#213 2021-06-09 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#217 2021-06-10 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#221 2021-06-11 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#225 2021-06-12 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#229 2021-06-13 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#233 2021-06-14 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#235 2021-06-14 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment

#239 2021-06-15 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#245 2021-06-16 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#247 2021-06-16 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#251 2021-06-17 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#259 2021-06-19 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#263 2021-06-20 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#267 2021-06-21 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#271 2021-06-22 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#277 2021-06-23 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#279 2021-06-23 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#283 2021-06-24 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#287 2021-06-25 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#291 2021-06-26 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#295 2021-06-27 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#299 2021-06-28 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#303 2021-06-29 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#311 2021-06-30 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#310 2021-06-30 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️
