Repository cagov/covid-static-data, pull requests merged in 2021-05, with the labels that each got.

#77 2021-05-12 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#79 2021-05-12 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#83 2021-05-13 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#88 2021-05-14 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#92 2021-05-15 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#96 2021-05-16 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#100 2021-05-17 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#104 2021-05-18 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#112 2021-05-19 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#114 2021-05-19 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#118 2021-05-20 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#127 2021-05-22 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#131 2021-05-23 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#135 2021-05-24 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#139 2021-05-25 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#145 2021-05-26 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#147 2021-05-26 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#152 2021-05-27 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#160 2021-05-29 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish at 9 a.m. ☀️

#164 2021-05-30 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#168 2021-05-31 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️
