Repository cagov/covid-static-data, pull requests merged in 2021-09, with the labels that each got.

#621 2021-09-01 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#620 2021-09-01 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#625 2021-09-01 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#627 2021-09-01 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#628 2021-09-02 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#632 2021-09-02 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#638 2021-09-03 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#636 2021-09-02 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#641 2021-09-03 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#642 2021-09-04 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#646 2021-09-04 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#647 2021-09-05 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#651 2021-09-05 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#655 2021-09-06 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#657 2021-09-07 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#660 2021-09-07 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#665 2021-09-08 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#663 2021-09-08 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#668 2021-09-08 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#670 2021-09-08 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#672 2021-09-08 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#673 2021-09-08 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Automatic Deployment, Publish at 8:50 a.m. ☀️

#675 2021-09-09 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#678 2021-09-09 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#680 2021-09-10 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#683 2021-09-10 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#685 2021-09-10 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment

#687 2021-09-11 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#690 2021-09-11 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#692 2021-09-12 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#695 2021-09-12 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#697 2021-09-13 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#700 2021-09-13 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#702 2021-09-14 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#705 2021-09-14 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#710 2021-09-15 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#708 2021-09-15 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#713 2021-09-15 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#715 2021-09-15 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#725 2021-09-16 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#726 2021-09-16 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#727 2021-09-17 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#731 2021-09-17 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#732 2021-09-18 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#736 2021-09-18 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#737 2021-09-19 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#741 2021-09-19 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#742 2021-09-20 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#746 2021-09-20 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#757 2021-09-22 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#761 2021-09-22 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#756 2021-09-22 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#763 2021-09-22 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#765 2021-09-23 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#769 2021-09-23 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#770 2021-09-24 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#774 2021-09-24 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#775 2021-09-25 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#777 2021-09-25 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#781 2021-09-26 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#785 2021-09-26 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#786 2021-09-27 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#790 2021-09-27 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#792 2021-09-28 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#796 2021-09-28 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#798 2021-09-28 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Automatic Deployment, Publish at 8:40 a.m. ☀️

#811 2021-09-29 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#803 2021-09-29 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Automatic Deployment, Publish at 8:45 a.m. ☀️

#817 2021-09-30 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:50 a.m. ☀️

#813 2021-09-30 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️
