Repository cagov/covid-static-data, pull requests merged in 2021-08, with the labels that each got.

#456 2021-08-01 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#460 2021-08-02 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#464 2021-08-03 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#470 2021-08-04 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9 a.m. ☀️

#472 2021-08-04 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Automatic Deployment, Publish ASAP ✅, Publish at 9:15 a.m. ☀️

#476 2021-08-05 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#480 2021-08-06 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#484 2021-08-07 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#488 2021-08-08 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#492 2021-08-09 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#493 2021-08-09 V2 Stats Update
  data/daily-stats-v2.json
Labels: Publish ASAP ✅, Automatic Deployment

#498 2021-08-10 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#504 2021-08-11 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#506 2021-08-11 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#512 2021-08-12 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#516 2021-08-13 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#520 2021-08-14 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#524 2021-08-15 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#528 2021-08-16 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#532 2021-08-17 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#535 2021-08-17 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#536 2021-08-17 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#537 2021-08-17 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#541 2021-08-18 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#543 2021-08-18 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#544 2021-08-18 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#545 2021-08-18 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#546 2021-08-18 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#550 2021-08-19 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#551 2021-08-19 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#555 2021-08-19 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#559 2021-08-20 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#563 2021-08-21 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#566 2021-08-22 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#571 2021-08-23 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#577 2021-08-24 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#573 2021-08-24 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#584 2021-08-25 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#586 2021-08-25 Vaccine HPI
  data/vaccine-hpi/v2/vaccine-hpi.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️

#588 2021-08-25 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Publish at 9 a.m. ☀️, Automatic Deployment

#580 2021-08-25 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#602 2021-08-28 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#603 2021-08-29 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#607 2021-08-29 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#608 2021-08-30 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#612 2021-08-30 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment

#613 2021-08-31 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 8:40 a.m. ☀️

#617 2021-08-31 V2 Stats Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish at 9 a.m. ☀️, Publish ASAP ✅, Automatic Deployment
