Repository cagov/covid-static-data, pull requests merged in 2021-12, with the labels that each got.

#1324 2021-12-08 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1340 2021-12-10 Variants Data Update
  data/dashboard/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1345 2021-12-10 Variants Data Update
  data/dashboard/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1411 2021-12-16 Variants Data Update
  data/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1453 2021-12-22 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1455 2021-12-22 Variants Data Update
  data/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1462 2021-12-23 V2 Stats Update
  data/daily-stats-v2.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1470 2021-12-25-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1473 2021-12-26-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1487 2021-12-28 equity dashboard chart data update (Staging)
  data/to-review/equitydash/equitytopboxdatav2.json
Labels: Automatic Deployment

#1489 2021-12-28 equity dashboard chart data update (Staging)
  data/to-review/equitydash/equitytopboxdatav2.json
Labels: Automatic Deployment
