Repository cagov/covid-static-data, pull requests merged in 2022-09, with the labels that each got.

#2553 2022-09-02 Variants Data Update
  data/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#2552 2022-09-02 Dashboard Summary Update
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#2551 2022-09-02 Postvax Data Update
  data/dashboard/postvax/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#2547 2022-09-02 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#2557 2022-09-02-Rollup
  data/chart-sandbox/test-file.txt
Labels: Publish ASAP ✅, Automatic Deployment, Rollup

#2559 2022-09-02-Rollup
  data/dashboard/postvax-v2/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#2566 2022-09-07-Rollup
  data/dashboard/postvax-v2/california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup
