Repository cagov/covid-static-data, pull requests merged in 2022-02, with the labels that each got.

#1769 2022-02-03 Variants Data Update
  data/variants/california.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1781 2022-02-06-Rollup
  data/daily-stats-v2.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1841 2022-02-15 equity dashboard chart data update (Staging)
  data/to-review/equitydash/equitytopboxdatav2.json
  data/to-review/equitydash/healthequity-alameda.json
  data/to-review/equitydash/healthequity-alpine.json
  data/to-review/equitydash/healthequity-amador.json
  data/to-review/equitydash/healthequity-butte.json
  data/to-review/equitydash/healthequity-calaveras.json
  data/to-review/equitydash/healthequity-california.json
  data/to-review/equitydash/healthequity-colusa.json
  data/to-review/equitydash/healthequity-contracosta.json
  data/to-review/equitydash/healthequity-delnorte.json
  data/to-review/equitydash/healthequity-eldorado.json
  data/to-review/equitydash/healthequity-fresno.json
  data/to-review/equitydash/healthequity-glenn.json
  data/to-review/equitydash/healthequity-humboldt.json
  data/to-review/equitydash/healthequity-imperial.json
  data/to-review/equitydash/healthequity-inyo.json
  data/to-review/equitydash/healthequity-kern.json
  data/to-review/equitydash/healthequity-kings.json
  data/to-review/equitydash/healthequity-lake.json
  data/to-review/equitydash/healthequity-lassen.json
  data/to-review/equitydash/healthequity-losangeles.json
  data/to-review/equitydash/healthequity-madera.json
  data/to-review/equitydash/healthequity-marin.json
  data/to-review/equitydash/healthequity-mariposa.json
  data/to-review/equitydash/healthequity-mendocino.json
  data/to-review/equitydash/healthequity-merced.json
  data/to-review/equitydash/healthequity-modoc.json
  data/to-review/equitydash/healthequity-mono.json
  data/to-review/equitydash/healthequity-monterey.json
  data/to-review/equitydash/healthequity-napa.json
  data/to-review/equitydash/healthequity-nevada.json
  data/to-review/equitydash/healthequity-orange.json
  data/to-review/equitydash/healthequity-placer.json
  data/to-review/equitydash/healthequity-plumas.json
  data/to-review/equitydash/healthequity-riverside.json
  data/to-review/equitydash/healthequity-sacramento.json
  data/to-review/equitydash/healthequity-sanbenito.json
  data/to-review/equitydash/healthequity-sanbernardino.json
  data/to-review/equitydash/healthequity-sandiego.json
  data/to-review/equitydash/healthequity-sanfrancisco.json
  data/to-review/equitydash/healthequity-sanjoaquin.json
  data/to-review/equitydash/healthequity-sanluisobispo.json
  data/to-review/equitydash/healthequity-sanmateo.json
  data/to-review/equitydash/healthequity-santabarbara.json
  data/to-review/equitydash/healthequity-santaclara.json
  data/to-review/equitydash/healthequity-santacruz.json
  data/to-review/equitydash/healthequity-shasta.json
  data/to-review/equitydash/healthequity-sierra.json
  data/to-review/equitydash/healthequity-siskiyou.json
  data/to-review/equitydash/healthequity-solano.json
  data/to-review/equitydash/healthequity-sonoma.json
  data/to-review/equitydash/healthequity-stanislaus.json
  data/to-review/equitydash/healthequity-sutter.json
  data/to-review/equitydash/healthequity-tehama.json
  data/to-review/equitydash/healthequity-trinity.json
  data/to-review/equitydash/healthequity-tulare.json
  data/to-review/equitydash/healthequity-tuolumne.json
  data/to-review/equitydash/healthequity-ventura.json
  data/to-review/equitydash/healthequity-yolo.json
  data/to-review/equitydash/healthequity-yuba.json
Labels: Automatic Deployment
