Repository cagov/covid-static-data, pull requests merged in 2022-01, with the labels that each got.

#1522 2022-01-01-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1525 2022-01-02-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1529 2022-01-03-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1586 2022-01-08-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1589 2022-01-09-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1603 2022-01-11 equity dashboard chart data update (Staging)
  data/to-review/equitydash/equitytopboxdatav2.json
Labels: Automatic Deployment

#1607 2022-01-11 equity dashboard chart data update (Staging)
  data/to-review/equitydash/equitytopboxdatav2.json
  data/to-review/equitydash/social-data-crowding.json
  data/to-review/equitydash/social-data-income.json
  data/to-review/equitydash/social-data-income_cumulative.json
  data/to-review/equitydash/social-data-insurance.json
Labels: Automatic Deployment

#1621 2022-01-12 equity dashboard chart data update
  data/reviewed/equitydash/equitytopboxdatav2.json
Labels: Automatic Deployment

#1638 2022-01-15-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1641 2022-01-16-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1681 2022-01-22-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1684 2022-01-23-Rollup
  data/daily-stats-v2.json
  data/dashboard/vaccines/sparkline.json
  data/infections-by-group/infections-by-group-california.json
Labels: Publish ASAP ✅, Automatic Deployment, Publish at 9:15 a.m. ☀️, Rollup

#1718 2022-01-27 Vaccines Sparkline Data Update
  data/dashboard/vaccines/sparkline.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️, Add to Rollup

#1719 2022-01-27 Dashboard Summary Update
  data/daily-stats-v2.json
Labels: Automatic Deployment, Publish at 9:15 a.m. ☀️
